CREATE DATABASE emp;
USE  emp;
DROP TABLE emp;
CREATE TABLE `emp`(
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `lastName` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名字',
    `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱',
    `gender` INT(11) NOT NULL DEFAULT 0 COMMENT '性别',
    `departName` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '单位名称',
    `birth` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '生日',
    PRIMARY KEY(`id`)
    
)ENGINE=INNODB CHARSET=utf8 COMMENT='人员表';

DROP TABLE fileOwn;
CREATE TABLE `fileOwn`(
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `personName` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '所属人员',
    `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
    `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '地址',
    `fileType` VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '文件类型',
    `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY(`id`)
)ENGINE=INNODB CHARSET=utf8 COMMENT='重建物品表';

DROP TABLE USER;
CREATE TABLE `user`(
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `username` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户姓名',
    `nickName` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户昵称',
    `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户密码',
    `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱',
    `phone` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '手机号',
    `icon` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像',
    `note` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
    `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `loginTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登录时间',
    PRIMARY KEY(`id`)
)ENGINE=INNODB CHARSET=utf8 COMMENT='用户表';
