server:
  port: 8088

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  messages:
    basename: i18n/login
  mvc:
    format:
      date: yyyy-MM-dd

  datasource:
    username: root
    password: 123456789xk
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 500MB
      # 设置单次请求文件的总大小
      max-request-size: 500MB

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml





